# This is a basic workflow to help you get started with Actions

name: Build and deploy to IBM Cloud Foundry

# Controls when the workflow will run
on: workflow_dispatch

env:
  IBM_CLOUD_REGION: us-south
  IBM_CLOUD_GROUP: default
  IBM_CLOUD_SPACE: dev
  IBM_CLOUD_ORG: cozzetimaximo@yahoo.com
  MANIFEST_NAME: manifest.yml 
  IBM_CLOUD_API: ${{secrets.IBM_CLOUD_API_KEY}}

defaults:
  run:
    working-directory: server
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish and Deploy
    runs-on: ubuntu-latest
